# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '3.7'

volumes:
  orderer0.example.com:
  peer0.org1.example.com:
  peer1.org1.example.com:
  peer2.org1.example.com:
  peer3.org1.example.com:
  peer4.org1.example.com:

networks:
  test:
    name: fabric_test

services:

  orderer0.example.com:
    container_name: orderer0.example.com
    image: hyperledger/fabric-orderer:latest
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_BOOTSTRAPMETHOD=none
      - ORDERER_CHANNELPARTICIPATION_ENABLED=true
      - ORDERER_ADMIN_TLS_ENABLED=true
      - ORDERER_ADMIN_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_ADMIN_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_ADMIN_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_ADMIN_TLS_CLIENTROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_ADMIN_LISTENADDRESS=0.0.0.0:17050
      - ORDERER_OPERATIONS_LISTENADDRESS=orderer0.example.com:27050
      - ORDERER_METRICS_PROVIDER=prometheus
    working_dir: /root
    command: orderer
    volumes:
        - ../organizations/ordererOrganizations/example.com/orderers/orderer0.example.com/msp:/var/hyperledger/orderer/msp
        - ../organizations/ordererOrganizations/example.com/orderers/orderer0.example.com/tls/:/var/hyperledger/orderer/tls
        - orderer0.example.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050
      - 17050:17050
      - 27050:27050
    networks:
      - test
    extra_hosts:
      # - "orderer0.example.com:192.168.128.50"
      - "orderer1.example.com:192.168.128.100"
      - "peer0.org1.example.com:192.168.128.50"
      - "peer1.org1.example.com:192.168.128.50"
      - "peer2.org1.example.com:192.168.128.50"
      - "peer3.org1.example.com:192.168.128.50"
      - "peer4.org1.example.com:192.168.128.50"
      - "peer0.org2.example.com:192.168.128.100"
      - "peer1.org2.example.com:192.168.128.100"
      - "peer2.org2.example.com:192.168.128.100"
      - "peer3.org2.example.com:192.168.128.100"
      - "peer4.org2.example.com:192.168.128.100"
    
  peer0.org1.example.com:
    container_name: peer0.org1.example.com
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CFG_PATH=/etc/hyperledger/peercfg
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variables
      - CORE_PEER_ID=peer0.org1.example.com
      - CORE_PEER_ADDRESS=peer0.org1.example.com:8050
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8050
      - CORE_PEER_CHAINCODEADDRESS=peer0.org1.example.com:18050
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:18050
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.example.com:8050
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.example.com:8050
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_OPERATIONS_LISTENADDRESS=peer0.org1.example.com:28050
      - CORE_METRICS_PROVIDER=prometheus
      - CHAINCODE_AS_A_SERVICE_BUILDER_CONFIG={"peername":"peer0org1"}
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
    volumes:
      - ../organizations/peerOrganizations/org1.example.com/peers/peer0.org1.example.com:/etc/hyperledger/fabric
      - peer0.org1.example.com:/var/hyperledger/production
    working_dir: /root
    command: peer node start
    ports:
      - 8050:8050
      - 28050:28050
    networks:
      - test
    extra_hosts:
      - "orderer0.example.com:192.168.128.50"
      - "orderer1.example.com:192.168.128.100"
      # - "peer0.org1.example.com:192.168.128.50"
      - "peer1.org1.example.com:192.168.128.50"
      - "peer2.org1.example.com:192.168.128.50"
      - "peer3.org1.example.com:192.168.128.50"
      - "peer4.org1.example.com:192.168.128.50"
      - "peer0.org2.example.com:192.168.128.100"
      - "peer1.org2.example.com:192.168.128.100"
      - "peer2.org2.example.com:192.168.128.100"
      - "peer3.org2.example.com:192.168.128.100"
      - "peer4.org2.example.com:192.168.128.100"

  peer1.org1.example.com:
    container_name: peer1.org1.example.com
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CFG_PATH=/etc/hyperledger/peercfg
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variables
      - CORE_PEER_ID=peer1.org1.example.com
      - CORE_PEER_ADDRESS=peer1.org1.example.com:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer1.org1.example.com:18051
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:18051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.example.com:8050
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.example.com:8050
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_OPERATIONS_LISTENADDRESS=peer1.org1.example.com:28051
      - CORE_METRICS_PROVIDER=prometheus
      - CHAINCODE_AS_A_SERVICE_BUILDER_CONFIG={"peername":"peer1org1"}
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
    volumes:
      - ../organizations/peerOrganizations/org1.example.com/peers/peer1.org1.example.com:/etc/hyperledger/fabric
      - peer1.org1.example.com:/var/hyperledger/production
    working_dir: /root
    command: peer node start
    ports:
      - 8051:8051
      - 28051:28051
    networks:
      - test
    extra_hosts:
      - "orderer0.example.com:192.168.128.50"
      - "orderer1.example.com:192.168.128.100"
      - "peer0.org1.example.com:192.168.128.50"
      # - "peer1.org1.example.com:192.168.128.50"
      - "peer2.org1.example.com:192.168.128.50"
      - "peer3.org1.example.com:192.168.128.50"
      - "peer4.org1.example.com:192.168.128.50"
      - "peer0.org2.example.com:192.168.128.100"
      - "peer1.org2.example.com:192.168.128.100"
      - "peer2.org2.example.com:192.168.128.100"
      - "peer3.org2.example.com:192.168.128.100"
      - "peer4.org2.example.com:192.168.128.100"

  peer2.org1.example.com:
    container_name: peer2.org1.example.com
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CFG_PATH=/etc/hyperledger/peercfg
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variables
      - CORE_PEER_ID=peer2.org1.example.com
      - CORE_PEER_ADDRESS=peer2.org1.example.com:8052
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_CHAINCODEADDRESS=peer2.org1.example.com:18052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:18052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.example.com:8050
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.example.com:8050
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_OPERATIONS_LISTENADDRESS=peer2.org1.example.com:28052
      - CORE_METRICS_PROVIDER=prometheus
      - CHAINCODE_AS_A_SERVICE_BUILDER_CONFIG={"peername":"peer2org1"}
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
    volumes:
      - ../organizations/peerOrganizations/org1.example.com/peers/peer2.org1.example.com:/etc/hyperledger/fabric
      - peer2.org1.example.com:/var/hyperledger/production
    working_dir: /root
    command: peer node start
    ports:
      - 8052:8052
      - 28052:28052
    networks:
      - test
    extra_hosts:
      - "orderer0.example.com:192.168.128.50"
      - "orderer1.example.com:192.168.128.100"
      - "peer0.org1.example.com:192.168.128.50"
      - "peer1.org1.example.com:192.168.128.50"
      # - "peer2.org1.example.com:192.168.128.50"
      - "peer3.org1.example.com:192.168.128.50"
      - "peer4.org1.example.com:192.168.128.50"
      - "peer0.org2.example.com:192.168.128.100"
      - "peer1.org2.example.com:192.168.128.100"
      - "peer2.org2.example.com:192.168.128.100"
      - "peer3.org2.example.com:192.168.128.100"
      - "peer4.org2.example.com:192.168.128.100"

  peer3.org1.example.com:
    container_name: peer3.org1.example.com
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CFG_PATH=/etc/hyperledger/peercfg
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variables
      - CORE_PEER_ID=peer3.org1.example.com
      - CORE_PEER_ADDRESS=peer3.org1.example.com:8053
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8053
      - CORE_PEER_CHAINCODEADDRESS=peer3.org1.example.com:18053
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:18053
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.example.com:8050
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.example.com:8050
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_OPERATIONS_LISTENADDRESS=peer3.org1.example.com:28053
      - CORE_METRICS_PROVIDER=prometheus
      - CHAINCODE_AS_A_SERVICE_BUILDER_CONFIG={"peername":"peer3org1"}
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
    volumes:
      - ../organizations/peerOrganizations/org1.example.com/peers/peer3.org1.example.com:/etc/hyperledger/fabric
      - peer3.org1.example.com:/var/hyperledger/production
    working_dir: /root
    command: peer node start
    ports:
      - 8053:8053
      - 28053:28053
    networks:
      - test
    extra_hosts:
      - "orderer0.example.com:192.168.128.50"
      - "orderer1.example.com:192.168.128.100"
      - "peer0.org1.example.com:192.168.128.50"
      - "peer1.org1.example.com:192.168.128.50"
      - "peer2.org1.example.com:192.168.128.50"
      # - "peer3.org1.example.com:192.168.128.50"
      - "peer4.org1.example.com:192.168.128.50"
      - "peer0.org2.example.com:192.168.128.100"
      - "peer1.org2.example.com:192.168.128.100"
      - "peer2.org2.example.com:192.168.128.100"
      - "peer3.org2.example.com:192.168.128.100"
      - "peer4.org2.example.com:192.168.128.100"

  peer4.org1.example.com:
    container_name: peer4.org1.example.com
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CFG_PATH=/etc/hyperledger/peercfg
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variables
      - CORE_PEER_ID=peer4.org1.example.com
      - CORE_PEER_ADDRESS=peer4.org1.example.com:8054
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8054
      - CORE_PEER_CHAINCODEADDRESS=peer4.org1.example.com:18054
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:18054
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.example.com:8050
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.example.com:8050
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_OPERATIONS_LISTENADDRESS=peer4.org1.example.com:28054
      - CORE_METRICS_PROVIDER=prometheus
      - CHAINCODE_AS_A_SERVICE_BUILDER_CONFIG={"peername":"peer4org1"}
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
    volumes:
      - ../organizations/peerOrganizations/org1.example.com/peers/peer4.org1.example.com:/etc/hyperledger/fabric
      - peer4.org1.example.com:/var/hyperledger/production
    working_dir: /root
    command: peer node start
    ports:
      - 8054:8054
      - 28054:28054
    networks:
      - test
    extra_hosts:
      - "orderer0.example.com:192.168.128.50"
      - "orderer1.example.com:192.168.128.100"
      - "peer0.org1.example.com:192.168.128.50"
      - "peer1.org1.example.com:192.168.128.50"
      - "peer2.org1.example.com:192.168.128.50"
      - "peer3.org1.example.com:192.168.128.50"
      # - "peer4.org1.example.com:192.168.128.50"
      - "peer0.org2.example.com:192.168.128.100"
      - "peer1.org2.example.com:192.168.128.100"
      - "peer2.org2.example.com:192.168.128.100"
      - "peer3.org2.example.com:192.168.128.100"
      - "peer4.org2.example.com:192.168.128.100"